# -*- coding: utf-8 -*-
"""AI Image Generation from Articles

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Um4Z3-RWsG4TDvlL7VnHaoBW1ouxDI-B
"""

!pip install diffusers transformers accelerate safetensors

import torch
from diffusers import StableDiffusionPipeline

device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Using device:", device)

pipe = StableDiffusionPipeline.from_pretrained(
    "runwayml/stable-diffusion-v1-5",
    torch_dtype=torch.float16 if device == "cuda" else torch.float32
)
pipe = pipe.to(device)

prompt = "realistic high resolution photo of a AI-powered tools embedded into daily life: marketing, education, gaming, therapy, shown in a collage, 4k, sharp focus"

result = pipe(prompt, num_inference_steps=25, guidance_scale=7.5)
image = result.images[0]
image.save("generated_imag12.png")
print("Saved generated_image12.png")